lang: null
title: Doom
logoText: Doom
api:
  crds:
    - docs/shared/crds/*.yaml
  openapis:
    - docs/shared/openapis/*.json
  references:
    v1alpha1.CodeQualityBranch: /apis/references/CodeQualityBranch#CodeQualityBranch
reference:
  - sources:
      - name: ref
        path: docs/usage/configuration.md#引用文档配置
sidebar:
  collapsed: false
