lang: null
title: Doom
logoText: Doom
api:
  crds:
    - shared/crds/*.yaml
  openapis:
    - shared/openapis/*.json
  references:
    v1alpha1.CodeQualityBranch: /apis/references/CodeQualityBranch#CodeQualityBranch
