apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  runTemplate:
    spec:
      timeouts:
        pipeline: 1h
      workspaces:
        - name: source
          volumeClaimTemplate:
            spec:
              storageClassName: topolvm
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
        - name: cache
          persistentVolumeClaim:
            claimName: build-cache
          subPath: yarn_cache
  workspaces:
    - name: source
    - name: cache
  tasks:
    - name: install-dependencies
      workspaces:
        - name: source
          workspace: source
        - name: cache
          workspace: cache
      taskSpec:
        steps:
          - image: build-harbor.alauda.cn/devops/builder-nodejs:18
            name: install
            imagePullPolicy: IfNotPresent
            workingDir: $(workspaces.source.path)
            resources:
              requests:
                cpu: 2
                memory: 4Gi
              limits:
                cpu: 4
                memory: 4Gi
            script: |
              # set -x
              export YARN_GLOBAL_FOLDER=/workspace/yarn_cache/global

              corepack enable

              yarn --immutable
    - name: build-docs
      runAfter:
        - install-dependencies
      workspaces:
        - name: source
          workspace: source
      taskSpec:
        steps:
          - image: build-harbor.alauda.cn/devops/builder-nodejs:18
            name: build
            imagePullPolicy: IfNotPresent
            workingDir: $(workspaces.source.path)
            resources:
              requests:
                cpu: 2
                memory: 4Gi
              limits:
                cpu: 4
                memory: 4Gi
            script: |
              # set -x
              yarn doom build
    - name: build-image
      runAfter:
        - build-docs
      workspaces:
        - name: source
          workspace: source
      taskRef:
        kind: ClusterTask
        name: alauda-build-image
      params:
        - name: container-image
          value: build-harbor.alauda.cn/idp/doom-docs
        - name: container-image-tag
          value: $(build.git.version.docker)
        - name: context
          value: dist
    - name: image-scan
      runAfter:
        - build-image
      workspaces:
        - name: source
          workspace: source
      taskRef:
        kind: ClusterTask
        name: alauda-image-scan
      params:
        - name: image_path
          value: build-harbor.alauda.cn/idp/doom-docs:$(build.git.version.docker)
