name: CI

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Build and Lint with Node.js ${{ matrix.node }} on ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - 18
          - 20
          - 22
          - 24
        os:
          - ubuntu-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install Dependencies
        run: yarn --immutable

      - name: Build and Lint
        run: |
          yarn build
          yarn run-p docs lint typecov
        env:
          PARSER_NO_WATCH: true
          RAW_TERMS_URL: ${{ secrets.RAW_TERMS_URL }}
