name: GitHub Pages

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Chinese Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js LTS
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          cache: yarn

      - name: Install Dependencies
        run: |
          yarn --immutable
          yarn workspace @alauda/doom-export playwright install

      - name: Build and Export
        run: |
          yarn build
          # export the docs as pdf first
          yarn docs:build -e
          yarn docs:export
          tempdir=$(mktemp -d)
          # copy the pdf to the tempdir
          cp -r ./dist/*.pdf $tempdir
          # then build the docs with pdf download link
          yarn docs:build -a -d -R -S
          # copy the pdf back to the dist folder
          cp -r $tempdir/*.pdf ./dist
          # remove the tempdir
          rm -rf $tempdir

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: doom.js.org
          full_commit_message: ${{ github.event.head_commit.message }}
